# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField()),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('played', models.BooleanField(default=False)),
                ('release_date', models.DateTimeField()),
                ('game_category', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
